<div class="row">
  <div class="col-8 mb-3 px-4">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Pesquisar por título ou descrição" id="search-input">
      <button class="btn btn-outline-primary" type="button" id="search-button">
        Pesquisar
      </button>
    </div>
  </div>
  <div class="col-4">
    <a href="/pages/problems/new.php">
      <i class="fe fe-plus"></i>
      Registrar Novo Problema
    </a>
  </div>
</div>

<table class="table">
  <thead>
    <th>ID</th>
    <th>Nome</th>
  </thead>
  <tbody>
    <tr>
      <td>#1</td>
      <td>Problema 1</td>
    </tr>
  </tbody>
</table>
