<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
    crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <script src="/assets/js/application.js"></script>
  <link rel="stylesheet" href="/assets/css/application.css">

  <title>Rastreador de Problemas</title>
</head>

<body>
  <nav class="navbar top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Rastreador de Problemas</a>
    </div>
  </nav>
  <main class="container-fluid row">
    <aside class="col-3 sidebar">
      <nav>
        <ul class="nav flex-column mt-1">
          <li class="nav-item">
            <a class="nav-link" href="/">Problemas</a>
          </li>
        </ul>
      </nav>
    </aside>
    <section class="offset-3 col-9 px-4">
      <header class="mb-3">
        <h1>
          <?= $title ?>
        </h1>
      </header>
      <?php include $view; ?>
    </section>
  </main>

</html>
